#!/bin/bash
set -e

APP_DB_USER=${POSTGRESQL_USER:-"docker"}
APP_DB_PASSWORD=${POSTGRESQL_PASSWORD:-"docker"}
APP_DB=${POSTGRESQL_DB:-"docker"}
POSTGRESQL_TEMPLATE=${POSTGRESQL_TEMPLATE:-"DEFAULT"}

POSTGRESQL_BIN=/usr/lib/postgresql/9.4/bin/postgres
POSTGRESQL_CONFIG_FILE=/etc/postgresql/9.4/main/postgresql.conf

POSTGRESQL_SINGLE="sudo -u postgres $POSTGRESQL_BIN --single --config-file=$POSTGRESQL_CONFIG_FILE"

$POSTGRESQL_SINGLE <<< "CREATE USER $APP_DB_USER WITH SUPERUSER;" > /dev/null
$POSTGRESQL_SINGLE <<< "ALTER USER $APP_DB_USER WITH PASSWORD '$APP_DB_PASSWORD';" > /dev/null
$POSTGRESQL_SINGLE <<< "CREATE DATABASE $APP_DB OWNER $APP_DB_USER TEMPLATE $POSTGRESQL_TEMPLATE;" > /dev/null

exec sudo -u postgres $POSTGRESQL_BIN --config-file=$POSTGRESQL_CONFIG_FILE

